version: '3.8'

services:
  php-apache:
    build: .
    container_name: mi_php_app
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
    - ./html:/var/www/html

volumes:
  mysql_data:
